version: '3.8'

services:
  # Add the node-js service

  executionandtracelog:
  # Location to the node.js dockerfile
    build:
      context: ./ExecutionAndTraceLog/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: eatl:${DOCKER_IMAGE_TAG}
    container_name: eatl_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3003:3010'
        #    volumes:
    volumes:
      - executionandtracelog:/home/openbackhaul/ExecutionAndTraceLog/database
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  typeapprovalregister:
    # Location to the node.js dockerfile
    build:
      context: ./TypeApprovalRegister/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: tar:${DOCKER_IMAGE_TAG}
    container_name: tar_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3002:3001'
    restart: on-failure
    volumes:
      - typeapprovalregister:/home/openbackhaul/typeApprovalRegister/database
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  registryoffice:
    # Location to the node.js dockerfile
    build:
      context: ./RegistryOffice/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: ro:${DOCKER_IMAGE_TAG}
    container_name: ro_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3001:3000'
    restart: on-failure
    volumes:
           - registryoffice:/home/openbackhaul/registryOffice/database
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  accessdministration:
    # Location to the node.js dockerfile
    build:
      context: ./AdministratorAdministration/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: aa:${DOCKER_IMAGE_TAG}
    container_name: aa_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3005:3004'
    restart: on-failure
    volumes:
      - accessdministration:/home/openbackhaul/administratorAdministration/database
      - accessdministration_app:/home/openbackhaul/administratorAdministration/application-data
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  applicationlayertopology:
    # Location to the node.js dockerfile
    build:
      context: ./ApplicationLayerTopology/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: alt:${DOCKER_IMAGE_TAG}
    container_name: alt_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3006:3005'
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - applicationlayertopology:/home/openbackhaul/applicationLayerTopology/database
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  oamlog:
    # Location to the node.js dockerfile
    build:
      context: ./OamLog/server/
        # Name of the dockerfile
      dockerfile: dockerfile
    image: ol:${DOCKER_IMAGE_TAG}
    container_name: ol_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3004:3011'
    restart: on-failure
    volumes:
      - oamlog:/home/openbackhaul/OamLog/database
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  operationkeymanagement:
  # Location to the node.js dockerfile
    build:
      context: ./OperationKeyManagement/server/
        # Name of the dockerfile
      dockerfile: Dockerfile
    image: okm:${DOCKER_IMAGE_TAG}
    container_name: okm_${DOCKER_IMAGE_TAG}
    ports:
       # Host port:Container port
      - '3007:8080'
    restart: on-failure
    volumes:
      - operationkeymanagement:/home/node/database
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Europe/Berlin"
    ports:
      - 3008:9200
      - 9300:9300
    restart: on-failure
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 45
    networks:
      - tinynetwork

  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    restart: on-failure
    healthcheck:
      test: curl -s http://kibana:5601 >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 45
    links:
      - elasticsearch:elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - tinynetwork
    environment:
      TZ: Europe/Berlin

  mdiproxy:
  # Location to the node.js dockerfile
    build:
      context: ./MultiDomainInventoryProxy/server/
      dockerfile: Dockerfile
    image: mdip
    container_name: mdip
    ports:
       # Host port:Container port
      - '4016:9093'
    environment:
      - "CONTROLLER_USER=${CONTROLLER_USER}"
      - "CONTROLLER_PASSWORD=${CONTROLLER_PASSWORD}"
      - "DEVICE_USER=${DEVICE_USER}"
      - "DEVICE_PASSWORD=${DEVICE_PASSWORD}"
      - "TZ=Europe/Berlin"
    restart: on-failure
    volumes:
      - /home/mentouser/workspace/mdip-logs:/home/openbackhaul/MultiDomainInventoryProxy/logs
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - tinynetwork

volumes:
  executionandtracelog:
  typeapprovalregister:
  registryoffice:
  accessdministration:
  accessdministration_app:
  applicationlayertopology:
  oamlog:
  operationkeymanagement:
  mdip-logs:

networks:
    tinynetwork:
        driver: bridge
